// ─── Crash reporting (Sentry) ────────────────────────────────────────────────
//
// MUST be imported first so it can wrap unhandled errors before any of our
// code runs. The DSN is read from env / a baked config; if it's empty,
// @sentry/electron quietly no-ops — safe to ship without configuring.
try {
  const Sentry = require('@sentry/electron/main');
  const dsn = process.env.SENTRY_DSN || '';
  if (dsn) {
    Sentry.init({
      dsn,
      release: `hzsec@${require('./package.json').version}`,
      // Ship only error+ events; sampling can be tuned later via env.
      tracesSampleRate: parseFloat(process.env.SENTRY_TRACES_RATE || '0'),
      // Strip filesystem paths from stack traces — they can contain user
      // home dirs which we'd rather not centralise.
      beforeSend(event) {
        if (event.exception?.values) {
          for (const v of event.exception.values) {
            v.stacktrace?.frames?.forEach(f => {
              if (f.filename) f.filename = f.filename.replace(/^.*[\\/]/, '');
            });
          }
        }
        return event;
      }
    });
  }
} catch (err) {
  // Sentry itself failing should never crash the app.
  console.warn('[sentry] init skipped:', err.message);
}

const { app, BrowserWindow, ipcMain, dialog, Notification, shell } = require('electron');
const path = require('path');
const fs = require('fs');

const { runSecurityScan } = require('./src/scanner/scan-engine');
const { createSmartMonitor, stopLiveMonitor } = require('./src/monitor/smart-monitor');
const { buildSafeReplacement, createBackup } = require('./src/fixes/safe-fixes');
const { handleAssistantMessage } = require('./src/assistant/assistant-handler');
const { scanFile } = require('./src/scanner/scan-file');
const { MODE_DEFINITIONS } = require('./src/config/modes');
const {
  initKnowledgeBase,
  getComplianceScore,
  getBreachCasesForFindings,
  getKbSyncStatus,
  syncCisaKev,
  syncNvdRecent,
  markFindingFixed,
  BREACH_CASES
} = require('./src/intelligence/knowledge-base');
const {
  saveApiKey, loadApiKey, clearApiKey,
  loadHistory, saveHistoryEntry, clearHistory,
  loadPrefs, savePrefs,
  appendAuditLog, loadAuditLog, clearAuditLog,
  getLicense, setLicense, clearLicense,
  getLicenseValidation, saveLicenseValidation
} = require('./src/storage/store');
const { listBackups } = require('./src/fixes/safe-fixes');
const { getAll: getSuppressions, add: addSuppression, remove: removeSuppression } = require('./src/storage/suppressions');

let mainWindow = null;
let monitorState = { watcher: null, targetPath: null, debounceTimers: {} };
let currentApiKey = '';
let currentLicenseKey = '';
let lastScanTarget = null;  // most recent scan root — used for assistant tool sandboxing

// Where the backend lives. Defaults to production; override via env for local
// dev (HZSEC_BACKEND_URL=http://localhost:8080 npm start).
const BACKEND_URL = process.env.HZSEC_BACKEND_URL || 'http://localhost:8080';
const ACCOUNT_BASE_URL = process.env.HZSEC_WEBSITE_URL || 'https://app.hzsec.io';

function getApiKey() { return currentApiKey; }

// Build the credential object the assistant expects. Proxy mode wins when a
// license key is set; falls back to direct Anthropic with the user's BYO key.
function getAssistantCreds() {
  if (currentLicenseKey) return { licenseKey: currentLicenseKey, backendUrl: BACKEND_URL };
  if (currentApiKey)     return { apiKey: currentApiKey };
  return null;
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1760,
    height: 1020,
    minWidth: 1400,
    minHeight: 800,
    backgroundColor: '#060d16',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false
    }
  });

  mainWindow.loadFile('index.html');
}

function sendToRenderer(channel, payload) {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send(channel, payload);
  }
}

function fireNotification(title, body) {
  if (Notification.isSupported()) {
    new Notification({ title, body: String(body).slice(0, 200) }).show();
  }
}

// ─── Auto-updates (electron-updater) ─────────────────────────────────────────
//
// The strategy:
//   1. On launch (after window is created) ask GitHub Releases for the latest
//      published version. autoUpdater knows where to look from the `publish`
//      block in package.json's "build" config.
//   2. If a newer version exists, autoUpdater downloads it in the background
//      and fires `update-downloaded`. We forward that to the renderer so it
//      can pop the "Update available" modal.
//   3. The renderer calls back via 'updater:install' when the user accepts —
//      we then call quitAndInstall() which restarts on the new version.
//
// In dev (electron .) the updater no-ops because there's no app-update.yml;
// that file is only generated by electron-builder during a real build.

let autoUpdater = null;
function setupAutoUpdater() {
  if (process.env.ELECTRON_DEV === '1' || !app.isPackaged) {
    console.log('[updater] skipped (not packaged)');
    return;
  }
  try {
    // Lazy-load so an unpackaged dev run doesn't have to install the dep.
    autoUpdater = require('electron-updater').autoUpdater;
  } catch (err) {
    console.warn('[updater] electron-updater not installed:', err.message);
    return;
  }

  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;

  autoUpdater.on('checking-for-update',  ()    => sendToRenderer('updater:status', { state: 'checking' }));
  autoUpdater.on('update-available',     (info) => sendToRenderer('updater:status', { state: 'available',  version: info?.version }));
  autoUpdater.on('update-not-available', ()    => sendToRenderer('updater:status', { state: 'current' }));
  autoUpdater.on('error',                (err) => {
    console.warn('[updater] error:', err.message);
    sendToRenderer('updater:status', { state: 'error', message: err.message });
  });
  autoUpdater.on('download-progress', (p) => {
    sendToRenderer('updater:progress', {
      percent:    Math.round(p.percent),
      bytesPerSec: p.bytesPerSecond,
      transferred: p.transferred,
      total:       p.total
    });
  });
  autoUpdater.on('update-downloaded', (info) => {
    sendToRenderer('updater:downloaded', {
      version:    info?.version,
      releaseDate: info?.releaseDate,
      releaseNotes: info?.releaseNotes
    });
  });

  // Fire the first check ~5s after launch — gives the renderer a moment to
  // mount + register the IPC listener before any download progress arrives.
  setTimeout(() => {
    autoUpdater.checkForUpdatesAndNotify().catch(err =>
      console.warn('[updater] initial check failed:', err.message)
    );
  }, 5_000);
}

ipcMain.handle('updater:check-now', async () => {
  if (!autoUpdater) return { ok: false, error: 'updater_not_initialized' };
  try {
    const r = await autoUpdater.checkForUpdates();
    return { ok: true, version: r?.updateInfo?.version || null };
  } catch (err) {
    return { ok: false, error: err.message };
  }
});

ipcMain.handle('updater:install', async () => {
  if (!autoUpdater) return { ok: false, error: 'updater_not_initialized' };
  // quitAndInstall(isSilent, isForceRunAfter) — second arg ensures the new
  // version launches automatically after the swap.
  setImmediate(() => autoUpdater.quitAndInstall(false, true));
  return { ok: true };
});

// Register the custom URL scheme so users can sign in via the website and
// have the license key handed back to the desktop app via `hzsec://license/...`.
// Single-instance lock ensures a deep-link click while the app is already
// running activates the existing window instead of spawning a duplicate.
if (process.defaultApp) {
  if (process.argv.length >= 2) {
    app.setAsDefaultProtocolClient('hzsec', process.execPath, [path.resolve(process.argv[1])]);
  }
} else {
  app.setAsDefaultProtocolClient('hzsec');
}

const gotLock = app.requestSingleInstanceLock();
if (!gotLock) {
  app.quit();
} else {
  app.on('second-instance', (_event, argv) => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
    // Windows / Linux deep links arrive in argv on second instance.
    const url = argv.find(a => typeof a === 'string' && a.startsWith('hzsec://'));
    if (url) handleDeepLink(url);
  });
}

// macOS deep links arrive via 'open-url'.
app.on('open-url', (event, url) => {
  event.preventDefault();
  handleDeepLink(url);
});

function handleDeepLink(rawUrl) {
  try {
    const u = new URL(rawUrl);
    if (u.protocol !== 'hzsec:') return;
    // hzsec://license/HZSEC-XXXX-...   (path = "/license/HZSEC-...")
    // hzsec://license?key=HZSEC-...    (also accept query-string variant)
    if (u.hostname === 'license' || u.pathname.startsWith('/license')) {
      const fromPath  = (u.pathname.replace(/^\/?license\/?/, '') || '').trim();
      const fromQuery = u.searchParams.get('key') || u.searchParams.get('licenseKey') || '';
      const key = (fromPath || fromQuery).toUpperCase();
      if (!key) return;
      setLicense(key);
      currentLicenseKey = key;
      // Validate in the background — don't block the deep-link return.
      validateLicenseKey(key).catch(() => {});
      sendToRenderer('license-updated', { licenseKey: key });
    }
  } catch (err) {
    console.warn('[deep-link] could not parse', rawUrl, err.message);
  }
}

// Load saved API key + license on startup
app.whenReady().then(() => {
  const savedKey = loadApiKey();
  if (savedKey) currentApiKey = savedKey;

  const savedLic = getLicense();
  if (savedLic) currentLicenseKey = savedLic;

  // Initialize security knowledge base
  initKnowledgeBase();

  createWindow();

  // Auto-updater starts checking ~5s after launch (see setupAutoUpdater).
  setupAutoUpdater();
});

app.on('window-all-closed', () => {
  stopLiveMonitor(monitorState);
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});

// ─── File selection ───────────────────────────────────────────────────────────

ipcMain.handle('select-folder', async () => {
  const result = await dialog.showOpenDialog({ properties: ['openDirectory'] });
  if (result.canceled || !result.filePaths.length) return null;
  return result.filePaths[0];
});

ipcMain.handle('select-file', async () => {
  const result = await dialog.showOpenDialog({ properties: ['openFile'] });
  if (result.canceled || !result.filePaths.length) return null;
  return result.filePaths[0];
});

// ─── Scanning ─────────────────────────────────────────────────────────────────

ipcMain.handle('run-scan', async (_, targetPath, options = {}) => {
  try {
    if (!targetPath) throw new Error('No target selected.');
    lastScanTarget = targetPath;  // remember for assistant tool scoping
    const data = await runSecurityScan(targetPath, options, monitorState.targetPath);

    // Save to history
    saveHistoryEntry(data);

    return { success: true, data };
  } catch (error) {
    return { success: false, error: error.message || 'Scan failed.' };
  }
});

ipcMain.handle('read-file-snippet', async (_, filePath, lineNumber, context = 4) => {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split(/\r?\n/);
    const start = Math.max(0, lineNumber - 1 - context);
    const end = Math.min(lines.length, lineNumber + context);
    const snippet = lines.slice(start, end).map((line, i) => {
      const actual = start + i + 1;
      return { lineNumber: actual, content: line, highlight: actual === lineNumber };
    });
    return { success: true, snippet };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

ipcMain.handle('read-full-file', async (_, filePath) => {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    return { success: true, content };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// ─── Fixes ────────────────────────────────────────────────────────────────────

ipcMain.handle('apply-safe-fix', async (_, issue) => {
  try {
    if (!issue?.filePath || !issue?.lineNumber) throw new Error('Issue missing file path or line number.');

    const filePath = path.resolve(issue.filePath);
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.split(/\r?\n/);
    const index = issue.lineNumber - 1;

    if (index < 0 || index >= lines.length) throw new Error('Line number out of range.');

    const originalLine = lines[index];
    const replacement = buildSafeReplacement(originalLine, issue);

    if (!replacement || replacement === originalLine) throw new Error('No safe automatic fix available.');

    const backupPath = createBackup(filePath);
    lines[index] = replacement;
    fs.writeFileSync(filePath, lines.join('\n'), 'utf8');

    appendAuditLog({
      action: 'fix-applied',
      target: filePath,
      detail: `Line ${issue.lineNumber} · ${issue.title} · fixType: ${issue.fixType}`,
      before: originalLine.trim(),
      after: replacement.trim()
    });

    return { success: true, filePath, backupPath, originalLine, newLine: replacement };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// Agentic fix — apply a batch of line replacements from the assistant's fix plan
ipcMain.handle('apply-agent-fixes', async (_, fixes) => {
  const results = [];

  for (const fix of fixes) {
    try {
      const filePath = path.resolve(fix.filePath);
      const content = fs.readFileSync(filePath, 'utf8');
      const lines = content.split(/\r?\n/);
      const index = fix.lineNumber - 1;

      if (index < 0 || index >= lines.length) {
        results.push({ ...fix, success: false, error: 'Line out of range.' });
        continue;
      }

      const backupPath = createBackup(filePath);
      lines[index] = fix.newLine;
      fs.writeFileSync(filePath, lines.join('\n'), 'utf8');

      results.push({ ...fix, success: true, backupPath });
    } catch (err) {
      results.push({ ...fix, success: false, error: err.message });
    }
  }

  const applied = results.filter(r => r.success);
  const failed  = results.filter(r => !r.success);

  if (applied.length > 0) {
    appendAuditLog({
      action: 'agent-fix-applied',
      detail: `${applied.length} fix(es) applied, ${failed.length} failed`,
      files: [...new Set(applied.map(r => path.basename(r.filePath || '')))].join(', ')
    });
  }

  return { success: true, results };
});

// ─── Export ───────────────────────────────────────────────────────────────────

ipcMain.handle('export-report', async (_, report) => {
  try {
    const result = await dialog.showSaveDialog({
      title: 'Export Security Report',
      defaultPath: `security-report-${Date.now()}.json`,
      filters: [{ name: 'JSON', extensions: ['json'] }]
    });

    if (result.canceled || !result.filePath) return { success: false, error: 'Export canceled.' };

    fs.writeFileSync(result.filePath, JSON.stringify(report, null, 2), 'utf8');

    appendAuditLog({
      action: 'export-completed',
      detail: `Report exported to ${result.filePath}`,
      findings: report.posture?.totalFindings ?? 0
    });

    return { success: true, filePath: result.filePath };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// ─── API Key ──────────────────────────────────────────────────────────────────

ipcMain.handle('set-api-key', async (_, key) => {
  currentApiKey = key || '';
  if (key) {
    saveApiKey(key);
    return { success: true, persisted: true };
  } else {
    clearApiKey();
    return { success: true, persisted: false };
  }
});

ipcMain.handle('get-api-key-status', async () => {
  // Returns enough context for the renderer to know which auth mode is
  // active. The renderer uses this to show the right UI in Settings.
  return {
    hasKey:        !!currentApiKey,
    hasLicense:    !!currentLicenseKey,
    activeMode:    currentLicenseKey ? 'proxy' : (currentApiKey ? 'byo' : 'none')
  };
});

// ─── License (HZSec managed-key flow) ────────────────────────────────────────

async function validateLicenseKey(key) {
  return new Promise((resolve) => {
    const url = new URL(BACKEND_URL + '/api/license/validate');
    const lib = url.protocol === 'http:' ? require('http') : require('https');
    const body = JSON.stringify({ licenseKey: key });
    const req = lib.request({
      hostname: url.hostname,
      port:     url.port || (url.protocol === 'http:' ? 80 : 443),
      path:     url.pathname,
      method:   'POST',
      headers:  { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) }
    }, res => {
      let data = '';
      res.on('data', c => { data += c; });
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (res.statusCode >= 200 && res.statusCode < 300 && parsed.valid) {
            saveLicenseValidation(parsed);
            resolve({ ok: true, ...parsed });
          } else {
            resolve({ ok: false, status: res.statusCode, ...parsed });
          }
        } catch (e) {
          resolve({ ok: false, error: 'parse_error: ' + e.message });
        }
      });
    });
    req.on('error', err => resolve({ ok: false, error: err.message }));
    req.setTimeout(8000, () => { req.destroy(); resolve({ ok: false, error: 'timeout' }); });
    req.write(body);
    req.end();
  });
}

ipcMain.handle('set-license', async (_, key) => {
  const trimmed = (key || '').trim().toUpperCase();
  if (!trimmed) return { success: false, error: 'license key is empty' };
  if (!/^HZSEC(-[A-Z2-9]{4}){4}$/.test(trimmed)) {
    return { success: false, error: 'invalid format — expected HZSEC-XXXX-XXXX-XXXX-XXXX' };
  }
  const validation = await validateLicenseKey(trimmed);
  if (!validation.ok) {
    return { success: false, error: validation.error || 'license rejected by backend', detail: validation };
  }
  setLicense(trimmed);
  currentLicenseKey = trimmed;
  appendAuditLog({ action: 'license-set', detail: 'License key saved + validated' });
  return { success: true, validation };
});

ipcMain.handle('get-license-status', async () => {
  if (!currentLicenseKey) return { hasLicense: false };
  const cached = getLicenseValidation();
  return {
    hasLicense:  true,
    licenseKey:  currentLicenseKey,
    validation:  cached || null,
    isCached:    !!cached
  };
});

ipcMain.handle('validate-license', async () => {
  if (!currentLicenseKey) return { ok: false, error: 'no license set' };
  return validateLicenseKey(currentLicenseKey);
});

ipcMain.handle('clear-license', async () => {
  clearLicense();
  currentLicenseKey = '';
  appendAuditLog({ action: 'license-cleared', detail: 'License key removed by user' });
  return { success: true };
});

ipcMain.handle('open-account-page', async () => {
  // Opens the website's sign-in page in the default browser. After sign-in
  // the website redirects back to `hzsec://license/HZSEC-...` which our
  // 'open-url' handler captures.
  await shell.openExternal(`${ACCOUNT_BASE_URL}/login?return=app`);
  return { success: true };
});

// ─── Assistant ────────────────────────────────────────────────────────────────

ipcMain.handle('assistant-message', async (_, { messages, findings, snippet, includeBreaches }) => {
  try {
    const result = await handleAssistantMessage({
      creds: getAssistantCreds(),
      messages,
      findings,
      snippet,
      scanRoot: lastScanTarget || monitorState.targetPath || null,
      includeBreaches: !!includeBreaches
    });
    return { success: true, ...result };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

// ─── History ──────────────────────────────────────────────────────────────────

ipcMain.handle('get-history', async () => {
  return { success: true, history: loadHistory() };
});

ipcMain.handle('clear-history', async () => {
  clearHistory();
  return { success: true };
});

ipcMain.handle('list-backups', async (_, filePath) => {
  return { success: true, backups: listBackups(filePath) };
});

// ─── Prefs ────────────────────────────────────────────────────────────────────

ipcMain.handle('get-prefs', async () => {
  return { success: true, prefs: loadPrefs() };
});

ipcMain.handle('save-prefs', async (_, prefs) => {
  const saved = savePrefs(prefs);
  return { success: true, prefs: saved };
});

// ─── Monitor ──────────────────────────────────────────────────────────────────

ipcMain.handle('start-monitor', async (_, targetPath) => {
  try {
    if (!targetPath) throw new Error('No target selected for monitoring.');

    function scanSingleFile(filePath) {
      return scanFile(filePath, MODE_DEFINITIONS.full, []);
    }

    function onEvent(payload) {
      sendToRenderer('monitor-event', payload);

      if (payload.type === 'ai-alert' && payload.aiMessage) {
        fireNotification(`⚠ ShieldOps: ${payload.filename}`, payload.aiMessage);
      } else if (payload.type === 'new-issues' && !currentApiKey) {
        const top = payload.findings[0];
        fireNotification(
          `⚠ ShieldOps: ${payload.findings.length} new issue(s) in ${payload.filename}`,
          top ? `${top.severity}: ${top.title}` : 'Open ShieldOps for details.'
        );
      }
    }

    monitorState = createSmartMonitor(targetPath, scanSingleFile, onEvent, getApiKey, monitorState);

    appendAuditLog({
      action: 'monitor-started',
      target: targetPath,
      detail: 'Live monitor activated'
    });

    return { success: true, targetPath: monitorState.targetPath };
  } catch (error) {
    return { success: false, error: error.message };
  }
});

ipcMain.handle('stop-monitor', async () => {
  stopLiveMonitor(monitorState);
  monitorState = { watcher: null, targetPath: null, debounceTimers: {} };
  appendAuditLog({ action: 'monitor-stopped', detail: 'Live monitor deactivated' });
  return { success: true };
});

// ─── Knowledge Base & Compliance ──────────────────────────────────────────────

ipcMain.handle('get-compliance-score', async (_, findings) => {
  try {
    const score = getComplianceScore(findings || []);
    return { success: true, score };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

ipcMain.handle('get-breach-cases', async (_, findings) => {
  try {
    const cases = getBreachCasesForFindings(findings || []);
    return { success: true, cases };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

ipcMain.handle('get-all-breaches', async () => {
  try {
    return { success: true, breaches: BREACH_CASES || [] };
  } catch (err) {
    return { success: false, error: err.message, breaches: [] };
  }
});

ipcMain.handle('get-kb-status', async () => {
  try {
    const status = getKbSyncStatus();
    return { success: true, status };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

ipcMain.handle('sync-kb', async () => {
  try {
    const [cisaCount, nvdCount] = await Promise.all([syncCisaKev(), syncNvdRecent()]);
    appendAuditLog({ action: 'kb-synced', detail: `CISA: ${cisaCount} entries, NVD: ${nvdCount} entries` });
    return { success: true, cisaCount, nvdCount };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

ipcMain.handle('mark-finding-fixed', async (_, findingId, method) => {
  try {
    markFindingFixed(findingId, method || 'manual');
    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

// ─── Suppression IPC ─────────────────────────────────────────────────────────

ipcMain.handle('get-suppressions', async () => {
  try {
    return { success: true, suppressions: getSuppressions() };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

ipcMain.handle('suppress-finding', async (_, suppression) => {
  try {
    const entry = addSuppression(suppression);
    appendAuditLog({ action: 'finding-suppressed', detail: `kind=${entry.kind} reason=${entry.reason} id=${entry.id}` });
    return { success: true, entry };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

ipcMain.handle('unsuppress-finding', async (_, suppressionId) => {
  try {
    removeSuppression(suppressionId);
    appendAuditLog({ action: 'finding-unsuppressed', detail: `id=${suppressionId}` });
    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
});

// ─── Audit Log IPC ────────────────────────────────────────────────────────────

ipcMain.handle('get-audit-log', async (_, limit) => {
  return { success: true, entries: loadAuditLog(limit || 300) };
});

ipcMain.handle('clear-audit-log', async () => {
  clearAuditLog();
  return { success: true };
});
