// ════════════════════════════════════════════════════════════════════════
// PLAYBOOKS — Phase 1B
// Finding-specific guidance injected into the assistant's system prompt.
// Keys match exact `title` strings from the scanners.
// ════════════════════════════════════════════════════════════════════════

const PLAYBOOKS = {
  // ── Secrets ──
  'AWS access key detected': {
    howAttackerExploits: 'Public scanners crawl GitHub continuously — keys are tested within minutes. Once valid, attackers run aws sts get-caller-identity to map permissions, then enumerate S3, RDS, IAM. Even private repos leak via stolen developer laptops or contractor handoffs.',
    howToFix: 'TWO STEPS — both required. (1) Rotate the key NOW in AWS IAM Console. (2) Replace with env var via AWS SDK default credential chain, AWS Secrets Manager, or for production, IAM roles attached to compute resources (no static keys).',
    commonMistakes: 'Just deleting the line and committing — git history still has the key. Renaming the variable but keeping the value. Adding to .gitignore AFTER the commit.'
  },
  'API key exposed in file': {
    howAttackerExploits: 'API keys grant whatever scope the issuing service allowed — often read access to user data, ability to send emails/SMS, or charge stored payment methods. Many APIs have no rate-limit on key holders.',
    howToFix: 'Revoke the key in the issuing service\'s dashboard. Move the new key to environment variables. For client-side code where env vars don\'t exist, the key shouldn\'t be there — proxy through your backend.',
    commonMistakes: 'Treating publishable keys (Stripe pk_live_) the same as live keys (sk_live_). Know which kind you have before deciding.'
  },
  'Secret value exposed': {
    howAttackerExploits: 'Hardcoded secrets — JWT signing keys, encryption keys, webhook secrets — let attackers forge auth tokens, decrypt stored data, or inject malicious webhook payloads. JWT secret leakage especially: an attacker mints admin tokens for any user.',
    howToFix: 'Rotate the secret everywhere it\'s referenced. Move to env vars backed by a secrets manager (AWS Secrets Manager, Vault, Doppler). For JWT, use 256+ bit keys generated by crypto.randomBytes.',
    commonMistakes: 'Rotating in one environment but leaving in another. Generating a "new secret" that\'s still derived from a guessable input.'
  },
  'Hardcoded password found': {
    howAttackerExploits: 'Hardcoded passwords for databases, internal services, or admin accounts give direct authenticated access — bypassing every other security layer. Often reused across environments.',
    howToFix: 'Rotate the password. Move credentials to env vars or a secrets manager. For databases, use IAM authentication (AWS RDS) or short-lived tokens (Vault dynamic secrets) where supported.',
    commonMistakes: 'Replacing with a "default that should be changed" placeholder — these get shipped. Using base64 encoding and calling it secure.'
  },
  'Private key material exposed': {
    howAttackerExploits: 'Private keys (SSH, TLS, GPG) let attackers impersonate the server, decrypt past traffic, or sign malicious code as a trusted identity. SSH keys grant immediate shell access to any host that trusts them.',
    howToFix: 'Treat as compromised: revoke (TLS via CA), remove from authorized_keys (SSH), or revoke from any signing service. Generate a new key pair, distribute the new public key, update dependent systems.',
    commonMistakes: 'Assuming a passphrase-protected key in source control is safe — can be cracked offline. Reusing the same SSH key across personal and work machines.'
  },
  'GitHub token exposed': {
    howAttackerExploits: 'PATs often have repo, workflow, and packages scopes — letting attackers push malicious code, modify CI/CD secrets, publish backdoored packages, or pivot to organization resources.',
    howToFix: 'Revoke the token in GitHub Settings → Developer settings → PATs. Audit the security log for unauthorized actions. Issue a new fine-grained token with minimum scope.',
    commonMistakes: 'Not auditing what the token might have done before revocation. Replacing a classic PAT with another classic PAT instead of switching to fine-grained.'
  },
  'Sensitive value in .env file': {
    howAttackerExploits: '.env files routinely get committed despite .gitignore — common scenarios: developer adds .env to gitignore AFTER first commit, force-adds for testing, or it leaks through Docker image layers.',
    howToFix: 'Verify .env is in .gitignore. If already committed, the values are compromised — rotate them all. Use .env.example with placeholders. For team sync, use a secrets manager (Doppler, 1Password, Infisical).',
    commonMistakes: 'Trusting that "private repo" means safe — leaks happen via stolen credentials, accidentally-public forks, employee turnover.'
  },

  // ── Configuration ──
  'Debug mode enabled': {
    howAttackerExploits: 'Debug mode in production exposes stack traces (revealing file paths, library versions), enables interactive debuggers reachable via web (Werkzeug debug PIN brute-force), or exposes admin endpoints meant for development.',
    howToFix: 'Set debug=false / DEBUG=False / NODE_ENV=production based on environment. Default to safe (debug off), only enable for explicit local dev.',
    commonMistakes: 'Toggling via an env var that isn\'t set in prod — defaults can quietly enable debug. Leaving "verbose error messages" on while debug is off.'
  },
  'Wildcard CORS policy': {
    howAttackerExploits: 'Access-Control-Allow-Origin: * combined with Allow-Credentials: true (often misconfigured together) lets any malicious site make authenticated requests on behalf of the user\'s browser session.',
    howToFix: 'Replace * with an explicit allow-list of trusted origins. Validate against a regex of known domains. Never combine wildcard origin with credentials. For public APIs, set Allow-Credentials: false and use bearer tokens.',
    commonMistakes: 'Echoing the request\'s Origin header back without validation — equivalent to wildcard. Using a permissive regex like /.*\\.example\\.com/ that matches malicious-example.com.attacker.com.'
  },
  'Wide network binding detected': {
    howAttackerExploits: 'Binding to 0.0.0.0 means the service listens on every network interface, including public ones. Internal-only databases, admin panels, and dev servers exposed this way get found by Shodan/Censys within hours.',
    howToFix: 'Bind to 127.0.0.1 / localhost for development. For production, bind to a specific interface or use a firewall (ufw, security groups, NetworkPolicy).',
    commonMistakes: 'Assuming a firewall is in place without verifying. Binding 0.0.0.0 inside a container and trusting the host firewall — fine until the container moves.'
  },
  'Transport encryption disabled': {
    howAttackerExploits: 'Disabled TLS/SSL means traffic is plaintext and can be intercepted on any hop. Login credentials, session cookies, API tokens are all extractable.',
    howToFix: 'Enable TLS 1.2+ everywhere. For internal services, use a service mesh (Istio, Linkerd) or mTLS via cert-manager. For development, mkcert generates trusted local certs.',
    commonMistakes: 'Allowing http:// fallback "for compatibility" — enables downgrade attacks. Disabling TLS verification (rejectUnauthorized: false) instead of fixing the cert chain.'
  },
  'Certificate verification disabled': {
    howAttackerExploits: 'When clients don\'t verify certs, an attacker on the network path can present any cert and the connection succeeds. Combined with DNS hijacking, this fully defeats TLS.',
    howToFix: 'Remove rejectUnauthorized: false / verify=False / InsecureSkipVerify: true. Fix the cert: install proper CA chain, use Let\'s Encrypt, or pin the specific cert if dealing with a known internal service.',
    commonMistakes: 'Using verification-disabled flags to "make tests work" then forgetting in production. Pinning to expired certs that need re-pinning every renewal.'
  },
  'Password stored in configuration': {
    howAttackerExploits: 'Config files get checked into version control, copied to laptops, included in Docker images, and end up in backups. A password in a config file has dozens of paths to attacker hands.',
    howToFix: 'Replace inline password with env var or secrets-manager reference. For YAML/JSON configs, support !env or ${SECRET} interpolation. Use framework-specific secret support (Rails credentials, Django SECRET_KEY env).',
    commonMistakes: 'Encrypting the config file with a key that\'s also in the repo. Using base64 obfuscation — trivially reversible.'
  },
  'Admin privilege default enabled': {
    howAttackerExploits: 'Default admin enables (root: true, is_admin: true) get inherited by new accounts unless explicitly cleared. Many breaches occur because a "test" admin account survived to production with default credentials.',
    howToFix: 'Default to least privilege. New accounts get user-level only; admin elevation requires explicit grant via a separate code path with audit log. Remove default-admin flags from configs.',
    commonMistakes: 'Documenting "remember to disable this" instead of disabling it. Tying admin status to a username pattern (admin*) that\'s easy to register.'
  },
  'Unencrypted endpoint reference': {
    howAttackerExploits: 'http:// URLs travel in plaintext and can be intercepted or modified in transit. Webhook endpoints especially: an attacker can fake "delivery" callbacks if they can MITM.',
    howToFix: 'Replace http:// with https:// for all external references. For internal-only services that don\'t support TLS, use a service mesh or run them on a private network.',
    commonMistakes: 'Hardcoding http://localhost — fine in dev, but ships when env-based switching is forgotten. Trusting "internal" networks more than they deserve.'
  },
  'Unresolved security TODO': {
    howAttackerExploits: 'TODO/FIXME comments mentioning auth/security/validation are a public roadmap of known weaknesses. Attackers grep for these in leaked source, npm packages, or decompiled apps.',
    howToFix: 'Either fix the issue or convert the TODO into a tracked ticket and remove the comment. Never ship security TODOs to production code.',
    commonMistakes: 'Leaving "// TODO: validate input" above unvalidated input — documents the bug for whoever reads the code, including attackers.'
  },

  // ── Code patterns ──
  'Child process execution path detected': {
    howAttackerExploits: 'exec/spawn/system calls including user input let attackers inject shell metacharacters (;, &&, $(), backticks) to run arbitrary commands. Even "sanitized" input can fail across platforms (bash vs cmd.exe).',
    howToFix: 'Avoid the shell: use execFile (Node) or subprocess.run with a list (Python, shell=False). Validate inputs against a strict allow-list. For Git, use a library (simple-git, GitPython) instead of shelling out.',
    commonMistakes: 'Trying to "escape" user input with regex — virtually always incomplete. Using exec with template strings.'
  },
  'Dynamic execution path detected': {
    howAttackerExploits: 'eval(), Function(), exec() with user input executes arbitrary code in the application\'s context. RCE is the worst-case finding — full takeover, data exfiltration, lateral movement.',
    howToFix: 'Replace eval-based dispatch with explicit handlers (object lookup, switch, route table). For dynamic config, use a sandboxed expression evaluator (jsep + safe interpreter, jexl) — never raw eval.',
    commonMistakes: 'Believing "I only call eval on data I generated" — the data path eventually includes user input. Using Function() thinking it\'s safer than eval.'
  },
  'Unsafe DOM injection pattern': {
    howAttackerExploits: 'innerHTML, document.write, dangerouslySetInnerHTML with attacker-controlled strings → stored or reflected XSS. Attackers inject scripts that steal cookies, tokens, or make auth\'d API calls.',
    howToFix: 'Use textContent for plain text. For HTML, use DOMPurify before innerHTML. In React, prefer JSX (auto-escaped). Set Content-Security-Policy with no unsafe-inline as defense in depth.',
    commonMistakes: 'Stripping <script> tags with regex — bypassed by SVG, event handlers, javascript: URIs. Trusting database-stored input because "we put it there" — the attacker put it there earlier.'
  },
  'Dynamic execution in front-end code': {
    howAttackerExploits: 'eval / new Function in browser code lets injected XSS persist as code rather than data. setTimeout/setInterval with string arguments behave the same.',
    howToFix: 'Replace eval with object lookups, JSON.parse for serialized data, or proper expression libraries. For setTimeout/setInterval, always pass a function reference, never a string.',
    commonMistakes: 'Using JSON.parse via eval as a polyfill — modern browsers have native JSON.parse. Calling eval on a user-pasted formula in a spreadsheet UI.'
  },
  'HTTP request from front-end code': {
    howAttackerExploits: 'fetch/XHR to http:// URLs from a https:// page — mixed content blocked by browsers, but if the call is to attacker-controlled server, they get session info via referrer or CORS leakage.',
    howToFix: 'Use https:// for all external API calls. For local dev against non-TLS backend, configure dev tools to ignore mixed content for that origin only.',
    commonMistakes: 'Hardcoding http://localhost:3000 in front-end code — works in dev, fails in prod where mixed-content blocking applies.'
  },

  // ── Hardening ──
  'SSH root login enabled': {
    howAttackerExploits: 'PermitRootLogin yes makes root directly brute-forceable. Attackers run username:password spray attacks at scale; "root" is the universal first guess.',
    howToFix: 'Set PermitRootLogin no in /etc/ssh/sshd_config. Create a regular user with sudo, SSH in as them. For automation, prohibit-password (key-only root) only if necessary.',
    commonMistakes: 'Setting prohibit-password and assuming it\'s as good as no — keys can leak too. Forgetting to reload sshd after changing the config.'
  },
  'SSH password authentication enabled': {
    howAttackerExploits: 'Password auth enables online brute force. Even with fail2ban, attackers rotate IPs (botnets, residential proxies) and grind through credentials.',
    howToFix: 'Set PasswordAuthentication no in sshd_config. Enforce key-based auth. For team access, use a CA-signed SSH cert system (Smallstep, Vault SSH, EC2 Instance Connect).',
    commonMistakes: 'Leaving password auth on as a fallback — if keys break, console access fixes it. Using weak SSH key types (RSA-1024, DSA).'
  },
  'Overly permissive file permissions': {
    howAttackerExploits: 'World-readable secrets let any local user — including compromised low-priv processes — read sensitive data. World-writable configs let attackers modify them.',
    howToFix: 'Restrict to 0600 (owner read/write only) for secrets. 0644 for public configs. Audit with ls -la, fix with chmod. For SSH: 0600 private keys, 0644 public.',
    commonMistakes: 'chmod 777 to fix permission errors without understanding what\'s needed. Setting permissions then having the application overwrite the file.'
  },
  'Passwordless sudo for all commands': {
    howAttackerExploits: 'NOPASSWD: ALL means anyone with shell access as that user instantly has root, with no password gate. Combined with SSH access, this turns user-level compromise into full root.',
    howToFix: 'Remove NOPASSWD entries from sudoers, or scope tightly to specific commands (NOPASSWD: /usr/bin/systemctl restart myapp). Use sudo -k in scripts to force re-auth.',
    commonMistakes: 'Granting passwordless sudo for a deployment script then forgetting to remove it. Using passwordless sudo for an account that also has SSH access.'
  }
};

function getPlaybookForFinding(finding) {
  if (!finding || !finding.title) return null;
  if (PLAYBOOKS[finding.title]) return { title: finding.title, ...PLAYBOOKS[finding.title] };
  const t = finding.title.toLowerCase();
  for (const [key, pb] of Object.entries(PLAYBOOKS)) {
    const k = key.toLowerCase();
    if (t.includes(k) || k.includes(t)) return { title: key, ...pb };
  }
  return null;
}

function getPlaybooksForFindings(findings = []) {
  const seen = new Set();
  const result = [];
  for (const f of findings) {
    const pb = getPlaybookForFinding(f);
    if (pb && !seen.has(pb.title)) {
      seen.add(pb.title);
      result.push(pb);
      if (result.length >= 5) break;
    }
  }
  return result;
}

module.exports = { PLAYBOOKS, getPlaybookForFinding, getPlaybooksForFindings };
